# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4282fd9e6089a0cc0efc11b925b078cb95de55111a8f21ffe21d85e1a0fa5c56c26869348af2b2a87cf5800948b4a8b465e42eb5cb3669229777a25afdde1f1

test:
  secret_key_base: 829861937444e3a0e23111d13de520ca83585b85a58e32a6fda0da75456c68f5b15a64bc41062b58177a08136ad3d33be84f4de0d8a4891617db539c9b945f26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
